### ISSUE TITLE
Add `Parameterized` tag to `LinuxProcess`, `LinuxService`, `WindowsProcess` & `WindowsService` 

### ISSUE THREAD

**Issue by CherfaElyes** [sentrysoftware/metricshub-community-connectors#138]
# Specification
Currently, there is no way to identify parameterized connectors other than by individually searching through each connector. To simplify this process, we are adding a `Parameterized` tag to these connectors.

**Comment by iguitton** [comment]
@CherfaElyes , @NassimBtk , @bertysentry : I suggest "customizable" instead of parameterized. What do you think?

**Comment by bertysentry** [comment]
I really don't think it's necessary to have a tag for identifying these connectors (nobody is going to search specifically for these). But if that was the case, we would use the tag: "configurable", I guess ;-)

**Comment by NassimBtk** [comment]
In the MetricsHub documentation, we initially provided a URL listing all the configurable (parameterized) connectors. I see that the documentation no longer references this page. It might not be necessary to group the configurable connectors since the first instinct is to search for a specific connector and then realize it can be configured using specific variables.
